<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>KSoft.T4</RootNamespace>
    <AssemblyName>KSoft.T4</AssemblyName>
    <AssemblyTitle>KSoft.T4</AssemblyTitle>
    <Product>KSoft.T4</Product>
    <TargetFramework>net481</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.VisualStudio.TextTemplating">
      <HintPath>$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TextTemplating\Microsoft.VisualStudio.TextTemplating.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
