<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <!--Using MSBuildProjectName here instead of AssemblyName, because AssemblyName won't have a value when executing Microsoft.PackageDependencyResolution.targets under Directory.Build.props setups-->
    <IntDir>$(VitaObjDir)$(VitaVisualStudioVersion)\$(MSBuildProjectName)\$(Configuration)\$(Platform)\</IntDir>
    <BaseIntermediateOutputPath>$(IntDir)</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(IntDir)</IntermediateOutputPath>
    <!-- <MSBuildProjectExtensionsPath>$(IntDir)</MSBuildProjectExtensionsPath> -->

    <FileAlignment>512</FileAlignment>
    <TargetFramework Condition="$(TargetFramework)==''">net9.0</TargetFramework>
    <LangVersion Condition=" '$(LangVersion)' == '' ">latest</LangVersion>
    <!-- <TargetFramework>net9.0-windows</TargetFramework> -->
    <!-- <LangVersion>7.3</LangVersion> -->
    <!-- <TargetFramework>netcoreapp2.1</TargetFramework> -->
    <!-- <TargetFrameworks>netcoreapp2.1;net48</TargetFrameworks> -->
    <!--FIXME: Need to figure out what we want to do here, as this format is not compatible with determinis-->
    <!-- <AssemblyVersion>0.0.%2a</AssemblyVersion> -->
  </PropertyGroup>

  <PropertyGroup Condition=" '$(VitaUseSolutionFamilyDirs)' == 'false' ">
    <OutDir>$(VitaBinPath)</OutDir>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(VitaUseSolutionFamilyDirs)' == 'true' ">
    <OutDir>$(VitaSolutionFamilyBinPath)</OutDir>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>$(OutDir)</OutputPath>
    <!--<DocumentationFile Condition=" '$(Configuration)' == 'Release' ">$(VitaRootDir)_lib\$(Configuration)\$(Platform)\$(AssemblyName)\$(AssemblyName).XML</DocumentationFile>-->
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>TRACE;$(DefineConstants)</DefineConstants>

    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <!--<CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>-->
    <!-- https://github.com/dotnet/roslyn-analyzers/issues/2003: when going from 2_9_8 to 2_9_9 I started getting threw an exception of type 'System.InvalidOperationException' with message 'Feature 'Flow-Analysis' is disabled.'. -->
    <Features>flow-analysis</Features>

  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration.Contains(Debug))' ">
    <Optimize>false</Optimize>
    <DebugType>full</DebugType>
    <DefineConstants>DEBUG;$(DefineConstants)</DefineConstants>
    <DebugSymbols>true</DebugSymbols>

  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration.Contains(Release))' ">
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(VitaPlatformType)' == 'AnyCPU' ">
    <PlatformTarget>AnyCpu</PlatformTarget>
    <!--Just don't do this shit because AnyCPU on x64 will be ran as 32-bit https://stackoverflow.com/a/39724213/444977-->
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(VitaPlatformType)' == 'x86' ">
    <PlatformTarget>x86</PlatformTarget>
    <DefineConstants>_WIN32;$(DefineConstants)</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(VitaPlatformType)' == 'x64' ">
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>_WIN64;$(DefineConstants)</DefineConstants>
  </PropertyGroup>
  <!-- Itanium -->
  <!-- ARM -->

  <ItemGroup>
    <Compile Include="$(VitaRootDir)KSoft\shared\source\KSoftAssemblyInfo.cs">
      <Link>Properties\KSoftAssemblyInfo.cs</Link>
    </Compile>
  </ItemGroup>
</Project>
