namespace KSoft.PropertyChanged.SourceGeneration;

internal static class GeneratorContracts
{
	public const string AttributeMetadataName = "KSoft.PropertyChanged.SourceGeneration.GeneratedPropertyChangedAttribute";
	public const string GeneratorName = "KSoft.PropertyChanged.SourceGeneration.PropertyChangedGenerator";
	public const string GeneratorVersion = "1.0.0.0";
	public const string BasicViewModelMetadataName = "KSoft.ObjectModel.BasicViewModel";
	public const string BackingFieldPropertyName = "BackingField";
	public const string AlwaysNotifyPropertyName = "AlwaysNotify";
	public const string CacheTypeName = "__PropertyChangedEventArgs";
	public const string ContractHintName = "KSoft.PropertyChanged.Contracts.g.cs";

	public const string ContractSource = """
		// <auto-generated/>

		namespace KSoft.PropertyChanged.SourceGeneration;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute(
			"KSoft.PropertyChanged.SourceGeneration.PropertyChangedGenerator",
			"1.0.0.0")]
		[global::System.AttributeUsageAttribute(
			global::System.AttributeTargets.Property,
			AllowMultiple = false,
			Inherited = false)]
		/// <summary>
		/// Generates a partial-property implementation that raises a cached property-change notification.
		/// </summary>
		/// <remarks>
		/// The containing type must directly derive from <c>KSoft.ObjectModel.BasicViewModel</c>.
		/// Unless <see cref="AlwaysNotify"/> is enabled, the generated setter chooses its equality helper from the
		/// declared property type:
		/// <list type="bullet">
		/// <item><description>Enums use KSoft's enum equality helper.</description></item>
		/// <item><description>
		/// Non-nullable value types implementing <c>IEquatable&lt;TSelf&gt;</c> use KSoft's equatable-value helper.
		/// </description></item>
		/// <item><description>
		/// Reference types, nullable value types, and all other types use
		/// <c>EqualityComparer&lt;T&gt;.Default</c>.
		/// </description></item>
		/// </list>
		/// Here, <c>T</c> is the declared property type. For example, an <c>object</c>-typed property uses
		/// <c>EqualityComparer&lt;object&gt;.Default</c>, including when its values are boxed value types. The default
		/// comparer treats null-to-value and value-to-null assignments as changes.
		/// </remarks>
		internal sealed class GeneratedPropertyChangedAttribute : global::System.Attribute
		{
			/// <summary>
			/// Gets or sets the name of an existing backing field. When omitted, the generated accessor uses the
			/// C# compiler-provided <c>field</c> storage.
			/// </summary>
			public string BackingField { get; set; }

			/// <summary>
			/// Gets or sets whether the generated setter assigns and raises a notification even when the old and new
			/// values compare equal.
			/// </summary>
			public bool AlwaysNotify { get; set; }
		}
		""";
}
