namespace KSoft.PropertyChanged.SourceGeneration;

internal static class GeneratorContracts
{
	public const string AttributeMetadataName = "KSoft.PropertyChanged.SourceGeneration.GeneratedPropertyChangedAttribute";
	public const string GeneratorName = "KSoft.PropertyChanged.SourceGeneration.PropertyChangedGenerator";
	public const string GeneratorVersion = "1.0.0.0";
	public const string BasicViewModelMetadataName = "KSoft.ObjectModel.BasicViewModel";
	public const string CacheTypeName = "__PropertyChangedEventArgs";
	public const string ContractHintName = "KSoft.PropertyChanged.Contracts.g.cs";

	public const string ContractSource = """
		// <auto-generated/>

		namespace KSoft.PropertyChanged.SourceGeneration;

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute(
			"KSoft.PropertyChanged.SourceGeneration.PropertyChangedGenerator",
			"1.0.0.0")]
		[global::System.AttributeUsageAttribute(
			global::System.AttributeTargets.Property,
			AllowMultiple = false,
			Inherited = false)]
		internal sealed class GeneratedPropertyChangedAttribute : global::System.Attribute
		{
			public string BackingField { get; set; }
		}
		""";
}
