using System.Text;
using System.Linq;
using KSoft.PropertyChanged.SourceGeneration.Diagnostics;
using KSoft.SourceGeneration.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace KSoft.PropertyChanged.SourceGeneration;

internal static class PropertyChangedEventArgsCacheGeneration
{
	private static readonly SymbolDisplayFormat sTypeDisplayFormat = new(
		globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
		typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
		genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
		miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

	public static void Initialize(IncrementalGeneratorInitializationContext context)
	{
		IncrementalValuesProvider<Candidate> candidates = context.SyntaxProvider.ForAttributeWithMetadataName(
			GeneratorContracts.EventArgsAttributeMetadataName,
			static (node, _) => node is PropertyDeclarationSyntax,
			static (attributeContext, _) => new Candidate(
				(IPropertySymbol)attributeContext.TargetSymbol,
				(PropertyDeclarationSyntax)attributeContext.TargetNode));

		context.RegisterSourceOutput(
			candidates,
			static (sourceContext, candidate) => Execute(sourceContext, candidate));
	}

	private static void Execute(SourceProductionContext context, Candidate candidate)
	{
		IPropertySymbol property = candidate.Property;
		INamedTypeSymbol type = property.ContainingType;
		Location location = candidate.Syntax.GetLocation();
		if (type.ContainingType != null
			|| type.Arity != 0
			|| type.TypeKind != TypeKind.Class
			|| candidate.Syntax.Parent is not ClassDeclarationSyntax typeDeclaration
			|| !typeDeclaration.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.PartialKeyword))
			|| typeDeclaration.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.FileKeyword))
			|| property.IsStatic
			|| property.IsIndexer
			|| property.ExplicitInterfaceImplementations.Length != 0
			|| candidate.Syntax.ExplicitInterfaceSpecifier != null)
		{
			context.ReportDiagnostic(Diagnostic.Create(
				DiagnosticDescriptors.UnsupportedTarget,
				location,
				property.Name,
				"cache-only generation requires an instance property in a top-level, non-generic partial class"));
			return;
		}

		string fieldName = EventArgsFieldName(property.Name);
		if (type.GetMembers(fieldName).Length != 0)
		{
			context.ReportDiagnostic(Diagnostic.Create(
				DiagnosticDescriptors.GeneratedMemberCollision,
				location,
				type.ToDisplayString(),
				fieldName));
			return;
		}

		string hintName = GeneratedSourceUtilities.CreateHintName(
			type,
			sTypeDisplayFormat,
			$"EventArgs.{property.Name}");
		context.AddSource(
			hintName,
			SourceText.From(BuildSource(typeDeclaration, property, fieldName), Encoding.UTF8));
	}

	private static string BuildSource(
		ClassDeclarationSyntax typeDeclaration,
		IPropertySymbol property,
		string fieldName)
	{
		var writer = new SourceWriter();
		writer.WriteLine("// <auto-generated/>");
		writer.WriteLine();

		string namespaceName = GeneratedSourceUtilities.NamespaceName(property.ContainingNamespace);
		if (namespaceName.Length != 0)
		{
			writer.WriteFileScopedNamespace(namespaceName);
			writer.WriteLine();
		}

		writer.WriteLine(
			$"{GeneratedSourceUtilities.ModifiersText(typeDeclaration.Modifiers)}class {GeneratedSourceUtilities.EscapeIdentifier(property.ContainingType.Name)}");
		using (writer.EnterBlock(SourceWriterBlockType.Braces))
		{
			writer.WriteLine(
				$"static readonly global::System.ComponentModel.PropertyChangedEventArgs {fieldName} =");
			using (writer.EnterBlock())
			{
				writer.WriteLine(
					$"new(nameof({GeneratedSourceUtilities.EscapeIdentifier(property.Name)}));");
			}
		}

		return writer.ToString();
	}

	private static string EventArgsFieldName(string propertyName) =>
		$"k{propertyName}ChangedEventArgs";

	private sealed class Candidate
	{
		public Candidate(IPropertySymbol property, PropertyDeclarationSyntax syntax)
		{
			Property = property;
			Syntax = syntax;
		}

		public IPropertySymbol Property { get; }
		public PropertyDeclarationSyntax Syntax { get; }
	}
}
