using System.Linq;
using KSoft.SourceGeneration.Descriptors;
using KSoft.SourceGeneration.Text;

namespace KSoft.SourceGeneration.SmokeTests;

internal static class SmokeSourceBuilder
{
	public const string HintName = "KSoft.SourceGeneration.Smoke.g.cs";

	public static string Build()
	{
		var writer = new SourceWriter();

		writer.WriteLine("// <auto-generated/>");
		writer.WriteLine("#nullable enable");
		writer.WriteLine();
		writer.WriteLine("namespace KSoft.SourceGeneration.SmokeTests");
		using (writer.EnterBlock(SourceWriterBlockType.Braces))
		{
			writer.WriteLine("internal static class KSoftSourceGenerationSmoke");
			using (writer.EnterBlock(SourceWriterBlockType.Braces))
			{
				writer.WriteLine("public const int NumberCount = " + PrimitiveCatalog.Numbers.Count + ";");
				writer.WriteLine("public const int PrimitiveCount = " + PrimitiveCatalog.Primitives.Count + ";");
				writer.WriteLine("public const int BittableUnsignedCount = "
					+ PrimitiveCatalog.BittableTypesUnsigned.Count + ";");
				writer.WriteLine("public const int BittableMajorWordCount = "
					+ PrimitiveCatalog.BittableTypesMajorWords.Count + ";");
				writer.WriteLine("public const string BittableUnsignedKeywords = \""
					+ string.Join(",", PrimitiveCatalog.BittableTypesUnsigned.Select(static x => x.Keyword)) + "\";");
			}
		}

		return writer.ToString();
	}
};
