using System.Text;

namespace KSoft.SourceGeneration.Text;

internal sealed class SourceWriter
{
	public const string IndentText = "\t";
	public const string NewLine = "\n";

	private readonly StringBuilder mBuilder = new();

	private int mIndentLevel;

	public int IndentLevel => mIndentLevel;

	public void WriteGeneratedFileHeader()
	{
		WriteLine("// <auto-generated/>");
		WriteLine("#nullable enable");
		WriteLine();
	}

	public void WriteFileScopedNamespace(string namespaceName)
	{
		ExceptionHelpers.ThrowIfNullOrEmpty(namespaceName, nameof(namespaceName));

		WriteLine($"namespace {namespaceName};");
	}

	public SourceWriterBlock EnterTypeDeclaration(string declaration)
	{
		ExceptionHelpers.ThrowIfNullOrEmpty(declaration, nameof(declaration));

		WriteLine(declaration);
		return EnterBlock(SourceWriterBlockType.BracesStatement);
	}

	public SourceWriterBlock EnterBlock(SourceWriterBlockType type = SourceWriterBlockType.NoBraces, int indentCount = 1)
	{
		ExceptionHelpers.ThrowIfNegative(indentCount, nameof(indentCount));

		if (type is SourceWriterBlockType.Braces or SourceWriterBlockType.BracesStatement)
		{
			WriteLine("{");
		}

		mIndentLevel += indentCount;

		return new SourceWriterBlock(this, type, indentCount);
	}

	public SourceWriterRegion EnterRegion(string name)
	{
		ExceptionHelpers.ThrowIfNullOrEmpty(name, nameof(name));

		WriteLine($"#region {name}");
		return new SourceWriterRegion(this);
	}

	public void WriteLine()
	{
		mBuilder.Append(NewLine);
	}

	public void WriteLine(string value)
	{
		ExceptionHelpers.ThrowIfNull(value, nameof(value));

		if (value.Length != 0)
		{
			AppendIndent();
		}

		mBuilder.Append(value);
		mBuilder.Append(NewLine);
	}

	public void WriteAttribute(string name)
	{
		ExceptionHelpers.ThrowIfNullOrEmpty(name, nameof(name));

		WriteLine($"[{name}]");
	}

	public void WritePurityAnnotation()
	{
		WriteAttribute("Contracts.Pure");
	}

	public void WriteContractsAliasUsing()
	{
		WriteLine("using Contracts = System.Diagnostics.Contracts;");
	}

	public void WriteContractShimAliasUsing()
	{
		// Generated sources keep Contract calls shim-aware while preserving the legacy T4 using shape.
		WriteLine("#if CONTRACTS_FULL_SHIM");
		WriteLine("using Contract = System.Diagnostics.ContractsShim.Contract;");
		WriteLine("#else");
		WriteLine("using Contract = System.Diagnostics.Contracts.Contract; // SHIM'D");
		WriteLine("#endif");
	}

	public void WriteXmlDocSummary(params string[] lines)
	{
		WriteXmlDocElement("summary", lines);
	}

	public void WriteXmlDocParam(string name, string text)
	{
		ExceptionHelpers.ThrowIfNullOrEmpty(name, nameof(name));
		ExceptionHelpers.ThrowIfNull(text, nameof(text));

		WriteLine($"/// <param name=\"{name}\">{text}</param>");
	}

	public void WriteXmlDocReturns(params string[] lines)
	{
		WriteXmlDocElement("returns", lines);
	}

	public override string ToString()
	{
		return mBuilder.ToString();
	}

	internal void ExitBlock(SourceWriterBlockType type, int indentCount)
	{
		ExceptionHelpers.ThrowIfNegative(indentCount, nameof(indentCount));
		ExceptionHelpers.ThrowIfGreaterThan(indentCount, mIndentLevel, nameof(indentCount));

		mIndentLevel -= indentCount;

		if (type == SourceWriterBlockType.Braces)
		{
			WriteLine("}");
		}
		else if (type == SourceWriterBlockType.BracesStatement)
		{
			WriteLine("};");
		}
	}

	internal void ExitRegion()
	{
		WriteLine("#endregion");
	}

	private void AppendIndent()
	{
		for (int x = 0; x < mIndentLevel; x++)
		{
			mBuilder.Append(IndentText);
		}
	}

	private void WriteXmlDocElement(string elementName, params string[] lines)
	{
		ExceptionHelpers.ThrowIfNullOrEmpty(elementName, nameof(elementName));
		ExceptionHelpers.ThrowIfNull(lines, nameof(lines));

		if (lines.Length == 0)
		{
			WriteLine($"/// <{elementName}></{elementName}>");
			return;
		}

		if (lines.Length == 1)
		{
			ExceptionHelpers.ThrowIfNull(lines[0], nameof(lines));

			WriteLine($"/// <{elementName}>{lines[0]}</{elementName}>");
			return;
		}

		WriteLine($"/// <{elementName}>");
		foreach (string line in lines)
		{
			ExceptionHelpers.ThrowIfNull(line, nameof(lines));

			WriteLine($"/// {line}");
		}

		WriteLine($"/// </{elementName}>");
	}
};
