using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Test.KSoft.SourceGeneration;

[TestClass]
public sealed partial class PropertyChangedGeneratorTests
{
	[TestMethod]
	public void CompilerFieldModeGeneratesOneSortedCacheAndCompilesTest()
	{
		TestRun run = Run("""
			#nullable enable
			using KSoft.PropertyChanged.SourceGeneration;
			namespace Example;
			public partial class SampleViewModel : KSoft.ObjectModel.BasicViewModel
			{
				[GeneratedPropertyChanged]
				public partial string? Zeta { get; set; }

				[GeneratedPropertyChanged]
				public partial int Alpha { get; set; }
			}
			""");
		string generated = PropertySource(run);
		AssertSourceEquivalent(
			"""
			// <auto-generated/>

			namespace Example;

			public partial class SampleViewModel
			{
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("KSoft.PropertyChanged.SourceGeneration.PropertyChangedGenerator", "1.0.0.0")]
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
				private static class __PropertyChangedEventArgs
				{
					internal static readonly global::System.ComponentModel.PropertyChangedEventArgs s_Alpha =
						new(nameof(Alpha));
					internal static readonly global::System.ComponentModel.PropertyChangedEventArgs s_Zeta =
						new(nameof(Zeta));
				}

				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("KSoft.PropertyChanged.SourceGeneration.PropertyChangedGenerator", "1.0.0.0")]
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
				public partial global::System.Int32 Alpha
				{
					get;
					set => base.SetFieldVal<global::System.Int32>(ref field, value, __PropertyChangedEventArgs.s_Alpha);
				}

				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("KSoft.PropertyChanged.SourceGeneration.PropertyChangedGenerator", "1.0.0.0")]
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
				public partial global::System.String Zeta
				{
					get;
					set => base.SetField<global::System.String>(ref field, value, __PropertyChangedEventArgs.s_Zeta);
				}
			}
			""",
			generated);
		AssertValid(run);
	}

	[TestMethod]
	public void ExplicitFieldModePreservesDirectStorageAndCompilesTest()
	{
		TestRun run = Run("""
			#nullable enable
			using KSoft.PropertyChanged.SourceGeneration;
			public partial class ExplicitViewModel : KSoft.ObjectModel.BasicViewModel
			{
				private string? mText;
				public ExplicitViewModel(string? text) { mText = text; }
				public string? ReadStorage() => mText;
				[GeneratedPropertyChanged(BackingField = nameof(mText))]
				public partial string? Text { get; set; }
			}
			""");
		string generated = PropertySource(run);
		StringAssert.Contains(generated, "get => mText;", StringComparison.Ordinal);
		StringAssert.Contains(generated, "set => base.SetField<global::System.String>(ref mText, value, __PropertyChangedEventArgs.s_Text);", StringComparison.Ordinal);
		Assert.IsFalse(generated.Contains("ref field", StringComparison.Ordinal));
		AssertValid(run);
	}

	[TestMethod]
	public void PropertyInitializerRemainsOnlyOnDefiningDeclarationTest()
	{
		TestRun run = Run("""
			using KSoft.PropertyChanged.SourceGeneration;
			public partial class InitializedViewModel : KSoft.ObjectModel.BasicViewModel
			{
				[GeneratedPropertyChanged]
				public partial bool Enabled { get; set; } = true;
			}
			""");
		string generated = PropertySource(run);
		Assert.IsFalse(generated.Contains("= true", StringComparison.Ordinal));
		StringAssert.Contains(generated, "get;", StringComparison.Ordinal);
		StringAssert.Contains(generated, "ref field", StringComparison.Ordinal);
		AssertValid(run);
	}

	[TestMethod]
	public void PrivateSetterAccessibilityIsRepeatedTest()
	{
		TestRun run = Run("""
			using KSoft.PropertyChanged.SourceGeneration;
			public partial class PrivateSetterViewModel : KSoft.ObjectModel.BasicViewModel
			{
				[GeneratedPropertyChanged]
				public partial int Value { get; private set; }
			}
			""");
		StringAssert.Contains(PropertySource(run), "private set => base.SetFieldVal<global::System.Int32>(ref field, value, __PropertyChangedEventArgs.s_Value);", StringComparison.Ordinal);
		AssertValid(run);
	}

	[TestMethod]
	[DataRow("string", "base.SetField<global::System.String>(ref field, value, __PropertyChangedEventArgs.s_Value);")]
	[DataRow("int", "base.SetFieldVal<global::System.Int32>(ref field, value, __PropertyChangedEventArgs.s_Value);")]
	[DataRow("global::System.DayOfWeek", "base.SetFieldEnum<global::System.DayOfWeek>(ref field, value, __PropertyChangedEventArgs.s_Value);")]
	public void PropertyTypeSelectsExactHelperTest(string typeName, string expectedCall)
	{
		string source = "using KSoft.PropertyChanged.SourceGeneration; public partial class ModeViewModel : KSoft.ObjectModel.BasicViewModel { [GeneratedPropertyChanged] public partial " + typeName + " Value { get; set; } }";
		TestRun run = Run(source);
		StringAssert.Contains(PropertySource(run), expectedCall, StringComparison.Ordinal);
		AssertValid(run);
	}

	[TestMethod]
	public void AlwaysNotifySelectsForcedGenericHelperTest()
	{
		TestRun run = Run("""
			using KSoft.PropertyChanged.SourceGeneration;
			public partial class ForcedViewModel : KSoft.ObjectModel.BasicViewModel
			{
				[GeneratedPropertyChanged(AlwaysNotify = true)]
				public partial int Value { get; set; }
			}
			""");
		StringAssert.Contains(
			PropertySource(run),
			"base.SetField<global::System.Int32>(ref field, value, __PropertyChangedEventArgs.s_Value, true);",
			StringComparison.Ordinal);
		AssertValid(run);
	}

	[TestMethod]
	public void ExplicitTypeArgumentAvoidsCompetingNonGenericOverloadTest()
	{
		TestRun run = Run("using KSoft.PropertyChanged.SourceGeneration; public partial class OverloadViewModel : KSoft.ObjectModel.BasicViewModel { [GeneratedPropertyChanged] public partial int Value { get; set; } }");
		StringAssert.Contains(
			PropertySource(run),
			"base.SetFieldVal<global::System.Int32>(ref field, value, __PropertyChangedEventArgs.s_Value);",
			StringComparison.Ordinal);
		AssertValid(run);
	}

	[TestMethod]
	public void HostLocalHelperDoesNotHideExplicitBaseCallTest()
	{
		TestRun run = Run("""
			using KSoft.PropertyChanged.SourceGeneration;
			public partial class HiddenHelperViewModel : KSoft.ObjectModel.BasicViewModel
			{
				private bool SetField<T>(
					ref T field,
					T value,
					global::System.ComponentModel.PropertyChangedEventArgs args)
				{
					field = value;
					return true;
				}

				[GeneratedPropertyChanged]
				public partial int Value { get; set; }
			}
			""");
		AssertValid(run);
	}

	[TestMethod]
	public void OutputIsDeterministicAcrossDriverRunsTest()
	{
		const string source = "using KSoft.PropertyChanged.SourceGeneration; namespace Determinism; public partial class Model : KSoft.ObjectModel.BasicViewModel { [GeneratedPropertyChanged] public partial int B { get; set; } [GeneratedPropertyChanged] public partial int A { get; set; } }";
		TestRun first = Run(source);
		TestRun second = Run(source);
		CollectionAssert.AreEqual(GeneratedOutputs(first), GeneratedOutputs(second));
		AssertValid(first);
		AssertValid(second);
	}

}
