using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Test.KSoft.SourceGeneration;

public sealed partial class PropertyChangedGeneratorTests
{
	[TestMethod]
	public void CaliburnProviderSupportsIndirectGenericAncestryAndVirtualNotificationTest()
	{
		TestRun run = Run("""
			#nullable enable
			using KSoft.PropertyChanged.SourceGeneration;

			public abstract class Intermediate<T> : Caliburn.Micro.PropertyChangedBase { }
			public static class Nested<T>
			{
				public abstract class Host : Intermediate<T> { }
			}

			public partial class CaliburnViewModel : Nested<int>.Host
			{
				private int mCount;
				private string? mText;
				private global::System.DayOfWeek mMode;

				[GeneratedPropertyChanged(BackingField = nameof(mCount))]
				public partial int Count { get; set; }

				[GeneratedPropertyChanged(BackingField = nameof(mText))]
				public partial string? Text { get; private set; }

				[GeneratedPropertyChanged(BackingField = nameof(mMode))]
				public partial global::System.DayOfWeek Mode { get; set; }

				public override void NotifyOfPropertyChange(string? propertyName = null)
				{
					base.NotifyOfPropertyChange(propertyName);
				}
			}
			""");

		CompilationUnitSyntax generated = GeneratedCompilationUnit(run);
		Assert.IsFalse(generated.DescendantNodes().OfType<ClassDeclarationSyntax>().Any(
			static declaration => declaration.Identifier.ValueText == "__PropertyChangedEventArgs"));
		Assert.HasCount(
			1,
			generated.DescendantNodes().OfType<MethodDeclarationSyntax>().Where(
				static method => method.Identifier.ValueText == "__PropertyChangedValuesEqual"));
		AssertSetterEquivalent(
			"""
			{
				if (__PropertyChangedValuesEqual(ref this.mCount, value))
				{
					return;
				}

				this.mCount = value;
				global::Caliburn.Micro.PropertyChangedBase propertyChangedNotifier = this;
				if (propertyChangedNotifier.IsNotifying)
				{
					propertyChangedNotifier.NotifyOfPropertyChange(nameof(Count));
				}
			}
			""",
			run,
			"Count");
		AssertSetterEquivalent(
			"""
			{
				if (global::System.Collections.Generic.EqualityComparer<global::System.DayOfWeek>.Default.Equals(this.mMode, value))
				{
					return;
				}

				this.mMode = value;
				global::Caliburn.Micro.PropertyChangedBase propertyChangedNotifier = this;
				if (propertyChangedNotifier.IsNotifying)
				{
					propertyChangedNotifier.NotifyOfPropertyChange(nameof(Mode));
				}
			}
			""",
			run,
			"Mode");
		AccessorDeclarationSyntax textSetter = GeneratedProperty(run, "Text")
			.AccessorList!.Accessors.Single(
				static accessor => accessor.IsKind(SyntaxKind.SetAccessorDeclaration));
		Assert.IsTrue(textSetter.Modifiers.Any(static modifier => modifier.IsKind(SyntaxKind.PrivateKeyword)));
		AssertValid(run);
	}

	[TestMethod]
	public void CaliburnProviderAlwaysNotifySkipsEqualityTest()
	{
		TestRun run = Run("""
			using KSoft.PropertyChanged.SourceGeneration;

			public partial class ForcedCaliburnViewModel : Caliburn.Micro.PropertyChangedBase
			{
				[GeneratedPropertyChanged(AlwaysNotify = true)]
					public partial int Value { get; set; }
			}
			""");
		AssertSourceEquivalent(
			"""
			// <auto-generated/>

			public partial class ForcedCaliburnViewModel
			{
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("KSoft.PropertyChanged.SourceGeneration.PropertyChangedGenerator", "1.0.0.0")]
				[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute]
				public partial global::System.Int32 Value
				{
					get;
					set
					{
						field = value;
						global::Caliburn.Micro.PropertyChangedBase propertyChangedNotifier = this;
						if (propertyChangedNotifier.IsNotifying)
						{
							propertyChangedNotifier.NotifyOfPropertyChange(nameof(Value));
						}
					}
				}
			}
			""",
			PropertySource(run));
		Assert.IsFalse(
			PropertySource(run).Contains("__PropertyChangedValuesEqual", StringComparison.Ordinal));
		AssertValid(run);
	}

	[TestMethod]
	public void CaliburnProviderInvalidApiFailsClosedTest()
	{
		AssertDiagnosticIds(
			Run(
				"""
				using KSoft.PropertyChanged.SourceGeneration;

				namespace Caliburn.Micro
				{
					public class PropertyChangedBase
					{
						public bool IsNotifying { get; set; }
						public void NotifyOfPropertyChange(string propertyName = null) { }
					}
				}

				public partial class InvalidCaliburnViewModel : Caliburn.Micro.PropertyChangedBase
				{
					[GeneratedPropertyChanged]
						public partial int Value { get; set; }
				}
				""",
				includeCaliburnReference: false),
			"KSPC0007");
	}

	[TestMethod]
	public void CaliburnProviderRejectsGenericAndRefNotificationApiTest()
	{
		AssertDiagnosticIds(
			Run(
				"""
				using KSoft.PropertyChanged.SourceGeneration;

				namespace Caliburn.Micro
				{
					public class PropertyChangedBase
					{
						public virtual bool IsNotifying { get; set; }
						public virtual void NotifyOfPropertyChange<T>(string propertyName = null) { }
						public virtual void NotifyOfPropertyChange(ref string propertyName) { }
					}
				}

				public partial class InvalidCaliburnViewModel : Caliburn.Micro.PropertyChangedBase
				{
					[GeneratedPropertyChanged]
						public partial int Value { get; set; }
				}
				""",
				includeCaliburnReference: false),
			"KSPC0007");
	}

	[TestMethod]
	public void CaliburnProviderExactReceiverIgnoresHiddenMembersTest()
	{
		TestRun run = Run("""
			using KSoft.PropertyChanged.SourceGeneration;

			public partial class HiddenCaliburnMembersViewModel : Caliburn.Micro.PropertyChangedBase
			{
				public new bool IsNotifying => false;
				public new void NotifyOfPropertyChange(string propertyName = null)
				{
					throw new global::System.InvalidOperationException();
				}

				[GeneratedPropertyChanged]
					public partial int Value { get; set; }
			}
			""");
		AssertSetterEquivalent(
			"""
			{
				if (__PropertyChangedValuesEqual(ref field, value))
				{
					return;
				}

				field = value;
				global::Caliburn.Micro.PropertyChangedBase propertyChangedNotifier = this;
				if (propertyChangedNotifier.IsNotifying)
				{
					propertyChangedNotifier.NotifyOfPropertyChange(nameof(Value));
				}
			}
			""",
			run,
			"Value");
		AssertValid(run);
	}

	[TestMethod]
	public void CaliburnProviderReceiverLocalDoesNotHideBackingFieldTest()
	{
		TestRun run = Run("""
			using KSoft.PropertyChanged.SourceGeneration;

			public partial class ReceiverNameCollisionViewModel : Caliburn.Micro.PropertyChangedBase
			{
				private int propertyChangedNotifier;

				[GeneratedPropertyChanged(BackingField = nameof(propertyChangedNotifier))]
					public partial int Value { get; set; }
			}
			""");
		AssertSetterEquivalent(
			"""
			{
				if (__PropertyChangedValuesEqual(ref this.propertyChangedNotifier, value))
				{
					return;
				}

				this.propertyChangedNotifier = value;
				global::Caliburn.Micro.PropertyChangedBase propertyChangedNotifier = this;
				if (propertyChangedNotifier.IsNotifying)
				{
					propertyChangedNotifier.NotifyOfPropertyChange(nameof(Value));
				}
			}
			""",
			run,
			"Value");
		AssertValid(run);
	}

	[TestMethod]
	public void CaliburnProviderValueEqualityHelperCollisionReportsKspc0006Test()
	{
		TestRun run = Run("""
			using KSoft.PropertyChanged.SourceGeneration;

			public partial class EqualityCollisionViewModel : Caliburn.Micro.PropertyChangedBase
			{
				private static bool __PropertyChangedValuesEqual<T>(ref T left, T right)
					where T : struct, global::System.IEquatable<T> => false;

				[GeneratedPropertyChanged]
					public partial int Value { get; set; }
			}
			""");
		AssertDiagnosticIds(run, "KSPC0006");
	}

	[TestMethod]
	public void CaliburnProviderMatchesPinnedRuntimeContractTest()
	{
		string assemblyName = "CaliburnProviderRuntimeFixture_" + Guid.NewGuid().ToString("N");
		TestRun run = Run("""
			#nullable disable
			using KSoft.PropertyChanged.SourceGeneration;

			public partial class RuntimeCaliburnViewModel : Caliburn.Micro.PropertyChangedBase
			{
				private int mValue;

				public int NotificationCalls { get; private set; }

				[GeneratedPropertyChanged(BackingField = nameof(mValue))]
					public partial int Value { get; set; }

				public override void NotifyOfPropertyChange(string propertyName = null)
				{
					NotificationCalls++;
					base.NotifyOfPropertyChange(propertyName);
				}
			}
			""",
			includeHost: false,
			assemblyName: assemblyName);
		AssertValid(run);

		using var assemblyStream = new MemoryStream();
		var emitResult = run.OutputCompilation.Emit(assemblyStream);
		Assert.IsTrue(
			emitResult.Success,
			string.Join(Environment.NewLine, emitResult.Diagnostics.Select(static diagnostic => diagnostic.ToString())));
		assemblyStream.Position = 0;

		System.Reflection.Assembly assembly =
			System.Runtime.Loader.AssemblyLoadContext.Default.LoadFromStream(assemblyStream);
		Type type = assembly.GetType("RuntimeCaliburnViewModel", throwOnError: true)!;
		var model = (Caliburn.Micro.PropertyChangedBase)Activator.CreateInstance(type)!;
		var propertyNames = new List<string?>();
		model.PropertyChanged += (_, args) => propertyNames.Add(args.PropertyName);
		System.Reflection.PropertyInfo valueProperty = type.GetProperty("Value")!;

		valueProperty.SetValue(model, 1);
		valueProperty.SetValue(model, 1);
		model.IsNotifying = false;
		valueProperty.SetValue(model, 2);

		Assert.AreEqual(2, valueProperty.GetValue(model));
		Assert.AreEqual(1, type.GetProperty("NotificationCalls")!.GetValue(model));
		CollectionAssert.AreEqual(new[] { "Value" }, propertyNames);
	}
}
