using KSoft.SourceGeneration.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Test.KSoft.SourceGeneration;

[TestClass]
public sealed class SourceWriterTests
{
	[TestMethod]
	public void BraceBlocksManageIndentationTest()
	{
		var writer = new SourceWriter();

		writer.WriteLine("namespace Example");
		using (writer.EnterBlock(SourceWriterBlockType.Braces))
		{
			writer.WriteLine("internal static class Type");
			using (writer.EnterBlock(SourceWriterBlockType.Braces))
			{
				writer.WriteLine("public const int Value = 1;");
			}
		}

		Assert.AreEqual(
			string.Join(SourceWriter.NewLine, [
				"namespace Example",
				"{",
				"\tinternal static class Type",
				"\t{",
				"\t\tpublic const int Value = 1;",
				"\t}",
				"}",
				"",
			]),
			writer.ToString());
	}

	[TestMethod]
	public void BracesStatementWritesTrailingSemicolonTest()
	{
		var writer = new SourceWriter();

		writer.WriteLine("internal sealed class Type");
		using (writer.EnterBlock(SourceWriterBlockType.BracesStatement))
		{
			writer.WriteLine("public const int Value = 1;");
		}

		Assert.AreEqual(
			string.Join(SourceWriter.NewLine, [
				"internal sealed class Type",
				"{",
				"\tpublic const int Value = 1;",
				"};",
				"",
			]),
			writer.ToString());
	}

	[TestMethod]
	public void GeneratedFileScaffoldHelpersWriteExpectedShapeTest()
	{
		var writer = new SourceWriter();

		writer.WriteGeneratedFileHeader();
		writer.WriteFileScopedNamespace("KSoft");
		writer.WriteLine();
		using (writer.EnterTypeDeclaration("partial class Bits"))
		{
			writer.WriteLine("public const int Value = 1;");
		}

		Assert.AreEqual(
			string.Join(SourceWriter.NewLine, [
				"// <auto-generated/>",
				"#nullable enable",
				"",
				"namespace KSoft;",
				"",
				"partial class Bits",
				"{",
				"\tpublic const int Value = 1;",
				"};",
				"",
			]),
			writer.ToString());
	}

	[TestMethod]
	public void RegionScopeWritesRegionDirectivesTest()
	{
		var writer = new SourceWriter();

		using (writer.EnterRegion("Example"))
		{
			writer.WriteLine("internal const int Value = 1;");
		}

		Assert.AreEqual(
			string.Join(SourceWriter.NewLine, [
				"#region Example",
				"internal const int Value = 1;",
				"#endregion",
				"",
			]),
			writer.ToString());
	}

	[TestMethod]
	public void UnindentedLineBypassesCurrentIndentationTest()
	{
		var writer = new SourceWriter();

		writer.WriteLine("if (value)");
		using (writer.EnterBlock(SourceWriterBlockType.Braces))
		{
			writer.WriteUnindentedLine("#pragma warning disable CA2208");
			writer.WriteLine("throw new InvalidOperationException();");
			writer.WriteUnindentedLine("#pragma warning restore CA2208");
		}

		Assert.AreEqual(
			string.Join(SourceWriter.NewLine, [
				"if (value)",
				"{",
				"#pragma warning disable CA2208",
				"\tthrow new InvalidOperationException();",
				"#pragma warning restore CA2208",
				"}",
				"",
			]),
			writer.ToString());
	}

	[TestMethod]
	public void XmlDocHelpersWriteSingleAndMultiLineElementsTest()
	{
		var writer = new SourceWriter();

		writer.WriteXmlDocSummary(
			"First summary line",
			"Second summary line");
		writer.WriteXmlDocParam("value", "Value to write");
		writer.WriteXmlDocReturns();
		writer.WritePurityAnnotation();

		Assert.AreEqual(
			string.Join(SourceWriter.NewLine, [
				"/// <summary>",
				"/// First summary line",
				"/// Second summary line",
				"/// </summary>",
				"/// <param name=\"value\">Value to write</param>",
				"/// <returns></returns>",
				"",
			]),
			writer.ToString());
	}
};
