<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="MSTest.Sdk/4.1.0">
	<PropertyGroup>
		<AppDesignerFolder>Properties</AppDesignerFolder>
		<RootNamespace>Test.KSoft.SourceGeneration</RootNamespace>
		<AssemblyName>Test.KSoft.SourceGeneration</AssemblyName>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\KSoft.SourceGeneration\KSoft.SourceGeneration.csproj" />
		<ProjectReference Include="..\KSoft.PropertyChanged.SourceGeneration\KSoft.PropertyChanged.SourceGeneration.csproj" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" PrivateAssets="all" />
	</ItemGroup>
</Project>
