<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>KSoft.Math</RootNamespace>
    <AssemblyName>KSoft.Math</AssemblyName>
    <CodeContractsAssemblyMode>1</CodeContractsAssemblyMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft\KSoft.csproj">
      <Project>{eb07f515-e27c-4768-8bd8-2829f657807e}</Project>
      <Name>KSoft</Name>
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
